version: '3.8'

services:
  web:
    build: .
    container_name: sija-pinjam-web
    restart: always
    ports:
      - "80:3000"
    environment:
      # Ini yang dibaca oleh process.env.MONGO_URI di server.js kamu
      - MONGO_URI=mongodb://sija_pinjam_db:27017/sija_pinjam_db
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: sija-pinjam-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: